// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: asr.proto

package ai.mawdoo3.salma.utils.asr;

public final class Asr {
  private Asr() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface speakOrBuilder extends
      // @@protoc_insertion_point(interface_extends:asr_service.speak)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.google.protobuf.BytesValue audioBytes = 1;</code>
     * @return Whether the audioBytes field is set.
     */
    boolean hasAudioBytes();
    /**
     * <code>.google.protobuf.BytesValue audioBytes = 1;</code>
     * @return The audioBytes.
     */
    com.google.protobuf.BytesValue getAudioBytes();

    /**
     * <code>.google.protobuf.Int32Value sampleRate = 2;</code>
     * @return Whether the sampleRate field is set.
     */
    boolean hasSampleRate();
    /**
     * <code>.google.protobuf.Int32Value sampleRate = 2;</code>
     * @return The sampleRate.
     */
    com.google.protobuf.Int32Value getSampleRate();

    /**
     * <code>.google.protobuf.StringValue id = 3;</code>
     * @return Whether the id field is set.
     */
    boolean hasId();
    /**
     * <code>.google.protobuf.StringValue id = 3;</code>
     * @return The id.
     */
    com.google.protobuf.StringValue getId();

    /**
     * <code>.google.protobuf.BoolValue first = 4;</code>
     * @return Whether the first field is set.
     */
    boolean hasFirst();
    /**
     * <code>.google.protobuf.BoolValue first = 4;</code>
     * @return The first.
     */
    com.google.protobuf.BoolValue getFirst();
  }
  /**
   * <pre>
   * Message Request (Both stream and Blob)
   * </pre>
   *
   * Protobuf type {@code asr_service.speak}
   */
  public  static final class speak extends
      com.google.protobuf.GeneratedMessageLite<
          speak, speak.Builder> implements
      // @@protoc_insertion_point(message_implements:asr_service.speak)
      speakOrBuilder {
    private speak() {
    }
    public static final int AUDIOBYTES_FIELD_NUMBER = 1;
    private com.google.protobuf.BytesValue audioBytes_;
    /**
     * <code>.google.protobuf.BytesValue audioBytes = 1;</code>
     */
    @Override
    public boolean hasAudioBytes() {
      return audioBytes_ != null;
    }
    /**
     * <code>.google.protobuf.BytesValue audioBytes = 1;</code>
     */
    @Override
    public com.google.protobuf.BytesValue getAudioBytes() {
      return audioBytes_ == null ? com.google.protobuf.BytesValue.getDefaultInstance() : audioBytes_;
    }
    /**
     * <code>.google.protobuf.BytesValue audioBytes = 1;</code>
     */
    private void setAudioBytes(com.google.protobuf.BytesValue value) {
      value.getClass();
  audioBytes_ = value;
      
      }
    /**
     * <code>.google.protobuf.BytesValue audioBytes = 1;</code>
     */
    @SuppressWarnings({"ReferenceEquality"})
    private void mergeAudioBytes(com.google.protobuf.BytesValue value) {
      value.getClass();
  if (audioBytes_ != null &&
          audioBytes_ != com.google.protobuf.BytesValue.getDefaultInstance()) {
        audioBytes_ =
          com.google.protobuf.BytesValue.newBuilder(audioBytes_).mergeFrom(value).buildPartial();
      } else {
        audioBytes_ = value;
      }
      
    }
    /**
     * <code>.google.protobuf.BytesValue audioBytes = 1;</code>
     */
    private void clearAudioBytes() {  audioBytes_ = null;
      
    }

    public static final int SAMPLERATE_FIELD_NUMBER = 2;
    private com.google.protobuf.Int32Value sampleRate_;
    /**
     * <code>.google.protobuf.Int32Value sampleRate = 2;</code>
     */
    @Override
    public boolean hasSampleRate() {
      return sampleRate_ != null;
    }
    /**
     * <code>.google.protobuf.Int32Value sampleRate = 2;</code>
     */
    @Override
    public com.google.protobuf.Int32Value getSampleRate() {
      return sampleRate_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : sampleRate_;
    }
    /**
     * <code>.google.protobuf.Int32Value sampleRate = 2;</code>
     */
    private void setSampleRate(com.google.protobuf.Int32Value value) {
      value.getClass();
  sampleRate_ = value;
      
      }
    /**
     * <code>.google.protobuf.Int32Value sampleRate = 2;</code>
     */
    @SuppressWarnings({"ReferenceEquality"})
    private void mergeSampleRate(com.google.protobuf.Int32Value value) {
      value.getClass();
  if (sampleRate_ != null &&
          sampleRate_ != com.google.protobuf.Int32Value.getDefaultInstance()) {
        sampleRate_ =
          com.google.protobuf.Int32Value.newBuilder(sampleRate_).mergeFrom(value).buildPartial();
      } else {
        sampleRate_ = value;
      }
      
    }
    /**
     * <code>.google.protobuf.Int32Value sampleRate = 2;</code>
     */
    private void clearSampleRate() {  sampleRate_ = null;
      
    }

    public static final int ID_FIELD_NUMBER = 3;
    private com.google.protobuf.StringValue id_;
    /**
     * <code>.google.protobuf.StringValue id = 3;</code>
     */
    @Override
    public boolean hasId() {
      return id_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue id = 3;</code>
     */
    @Override
    public com.google.protobuf.StringValue getId() {
      return id_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : id_;
    }
    /**
     * <code>.google.protobuf.StringValue id = 3;</code>
     */
    private void setId(com.google.protobuf.StringValue value) {
      value.getClass();
  id_ = value;
      
      }
    /**
     * <code>.google.protobuf.StringValue id = 3;</code>
     */
    @SuppressWarnings({"ReferenceEquality"})
    private void mergeId(com.google.protobuf.StringValue value) {
      value.getClass();
  if (id_ != null &&
          id_ != com.google.protobuf.StringValue.getDefaultInstance()) {
        id_ =
          com.google.protobuf.StringValue.newBuilder(id_).mergeFrom(value).buildPartial();
      } else {
        id_ = value;
      }
      
    }
    /**
     * <code>.google.protobuf.StringValue id = 3;</code>
     */
    private void clearId() {  id_ = null;
      
    }

    public static final int FIRST_FIELD_NUMBER = 4;
    private com.google.protobuf.BoolValue first_;
    /**
     * <code>.google.protobuf.BoolValue first = 4;</code>
     */
    @Override
    public boolean hasFirst() {
      return first_ != null;
    }
    /**
     * <code>.google.protobuf.BoolValue first = 4;</code>
     */
    @Override
    public com.google.protobuf.BoolValue getFirst() {
      return first_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : first_;
    }
    /**
     * <code>.google.protobuf.BoolValue first = 4;</code>
     */
    private void setFirst(com.google.protobuf.BoolValue value) {
      value.getClass();
  first_ = value;
      
      }
    /**
     * <code>.google.protobuf.BoolValue first = 4;</code>
     */
    @SuppressWarnings({"ReferenceEquality"})
    private void mergeFirst(com.google.protobuf.BoolValue value) {
      value.getClass();
  if (first_ != null &&
          first_ != com.google.protobuf.BoolValue.getDefaultInstance()) {
        first_ =
          com.google.protobuf.BoolValue.newBuilder(first_).mergeFrom(value).buildPartial();
      } else {
        first_ = value;
      }
      
    }
    /**
     * <code>.google.protobuf.BoolValue first = 4;</code>
     */
    private void clearFirst() {  first_ = null;
      
    }

    public static Asr.speak parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Asr.speak parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Asr.speak parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Asr.speak parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Asr.speak parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Asr.speak parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Asr.speak parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Asr.speak parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Asr.speak parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Asr.speak parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Asr.speak parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Asr.speak parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(Asr.speak prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Message Request (Both stream and Blob)
     * </pre>
     *
     * Protobuf type {@code asr_service.speak}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Asr.speak, Builder> implements
        // @@protoc_insertion_point(builder_implements:asr_service.speak)
        Asr.speakOrBuilder {
      // Construct using asr_service.Asr.speak.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.google.protobuf.BytesValue audioBytes = 1;</code>
       */
      @Override
      public boolean hasAudioBytes() {
        return instance.hasAudioBytes();
      }
      /**
       * <code>.google.protobuf.BytesValue audioBytes = 1;</code>
       */
      @Override
      public com.google.protobuf.BytesValue getAudioBytes() {
        return instance.getAudioBytes();
      }
      /**
       * <code>.google.protobuf.BytesValue audioBytes = 1;</code>
       */
      public Builder setAudioBytes(com.google.protobuf.BytesValue value) {
        copyOnWrite();
        instance.setAudioBytes(value);
        return this;
        }
      /**
       * <code>.google.protobuf.BytesValue audioBytes = 1;</code>
       */
      public Builder setAudioBytes(
          com.google.protobuf.BytesValue.Builder builderForValue) {
        copyOnWrite();
        instance.setAudioBytes(builderForValue.build());
        return this;
      }
      /**
       * <code>.google.protobuf.BytesValue audioBytes = 1;</code>
       */
      public Builder mergeAudioBytes(com.google.protobuf.BytesValue value) {
        copyOnWrite();
        instance.mergeAudioBytes(value);
        return this;
      }
      /**
       * <code>.google.protobuf.BytesValue audioBytes = 1;</code>
       */
      public Builder clearAudioBytes() {  copyOnWrite();
        instance.clearAudioBytes();
        return this;
      }

      /**
       * <code>.google.protobuf.Int32Value sampleRate = 2;</code>
       */
      @Override
      public boolean hasSampleRate() {
        return instance.hasSampleRate();
      }
      /**
       * <code>.google.protobuf.Int32Value sampleRate = 2;</code>
       */
      @Override
      public com.google.protobuf.Int32Value getSampleRate() {
        return instance.getSampleRate();
      }
      /**
       * <code>.google.protobuf.Int32Value sampleRate = 2;</code>
       */
      public Builder setSampleRate(com.google.protobuf.Int32Value value) {
        copyOnWrite();
        instance.setSampleRate(value);
        return this;
        }
      /**
       * <code>.google.protobuf.Int32Value sampleRate = 2;</code>
       */
      public Builder setSampleRate(
          com.google.protobuf.Int32Value.Builder builderForValue) {
        copyOnWrite();
        instance.setSampleRate(builderForValue.build());
        return this;
      }
      /**
       * <code>.google.protobuf.Int32Value sampleRate = 2;</code>
       */
      public Builder mergeSampleRate(com.google.protobuf.Int32Value value) {
        copyOnWrite();
        instance.mergeSampleRate(value);
        return this;
      }
      /**
       * <code>.google.protobuf.Int32Value sampleRate = 2;</code>
       */
      public Builder clearSampleRate() {  copyOnWrite();
        instance.clearSampleRate();
        return this;
      }

      /**
       * <code>.google.protobuf.StringValue id = 3;</code>
       */
      @Override
      public boolean hasId() {
        return instance.hasId();
      }
      /**
       * <code>.google.protobuf.StringValue id = 3;</code>
       */
      @Override
      public com.google.protobuf.StringValue getId() {
        return instance.getId();
      }
      /**
       * <code>.google.protobuf.StringValue id = 3;</code>
       */
      public Builder setId(com.google.protobuf.StringValue value) {
        copyOnWrite();
        instance.setId(value);
        return this;
        }
      /**
       * <code>.google.protobuf.StringValue id = 3;</code>
       */
      public Builder setId(
          com.google.protobuf.StringValue.Builder builderForValue) {
        copyOnWrite();
        instance.setId(builderForValue.build());
        return this;
      }
      /**
       * <code>.google.protobuf.StringValue id = 3;</code>
       */
      public Builder mergeId(com.google.protobuf.StringValue value) {
        copyOnWrite();
        instance.mergeId(value);
        return this;
      }
      /**
       * <code>.google.protobuf.StringValue id = 3;</code>
       */
      public Builder clearId() {  copyOnWrite();
        instance.clearId();
        return this;
      }

      /**
       * <code>.google.protobuf.BoolValue first = 4;</code>
       */
      @Override
      public boolean hasFirst() {
        return instance.hasFirst();
      }
      /**
       * <code>.google.protobuf.BoolValue first = 4;</code>
       */
      @Override
      public com.google.protobuf.BoolValue getFirst() {
        return instance.getFirst();
      }
      /**
       * <code>.google.protobuf.BoolValue first = 4;</code>
       */
      public Builder setFirst(com.google.protobuf.BoolValue value) {
        copyOnWrite();
        instance.setFirst(value);
        return this;
        }
      /**
       * <code>.google.protobuf.BoolValue first = 4;</code>
       */
      public Builder setFirst(
          com.google.protobuf.BoolValue.Builder builderForValue) {
        copyOnWrite();
        instance.setFirst(builderForValue.build());
        return this;
      }
      /**
       * <code>.google.protobuf.BoolValue first = 4;</code>
       */
      public Builder mergeFirst(com.google.protobuf.BoolValue value) {
        copyOnWrite();
        instance.mergeFirst(value);
        return this;
      }
      /**
       * <code>.google.protobuf.BoolValue first = 4;</code>
       */
      public Builder clearFirst() {  copyOnWrite();
        instance.clearFirst();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:asr_service.speak)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Asr.speak();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "audioBytes_",
              "sampleRate_",
              "id_",
              "first_",
            };
            String info =
                "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\t\u0002\t\u0003" +
                "\t\u0004\t";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<Asr.speak> parser = PARSER;
          if (parser == null) {
            synchronized (Asr.speak.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<Asr.speak>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:asr_service.speak)
    private static final Asr.speak DEFAULT_INSTANCE;
    static {
      speak defaultInstance = new speak();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        speak.class, defaultInstance);
    }

    public static Asr.speak getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<speak> PARSER;

    public static com.google.protobuf.Parser<speak> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface transcription_streamOrBuilder extends
      // @@protoc_insertion_point(interface_extends:asr_service.transcription_stream)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.google.protobuf.StringValue text = 1;</code>
     * @return Whether the text field is set.
     */
    boolean hasText();
    /**
     * <code>.google.protobuf.StringValue text = 1;</code>
     * @return The text.
     */
    com.google.protobuf.StringValue getText();

    /**
     * <code>.google.protobuf.StringValue id = 2;</code>
     * @return Whether the id field is set.
     */
    boolean hasId();
    /**
     * <code>.google.protobuf.StringValue id = 2;</code>
     * @return The id.
     */
    com.google.protobuf.StringValue getId();

    /**
     * <code>.google.protobuf.BoolValue final = 3;</code>
     * @return Whether the final field is set.
     */
    boolean hasFinal();
    /**
     * <code>.google.protobuf.BoolValue final = 3;</code>
     * @return The final.
     */
    com.google.protobuf.BoolValue getFinal();
  }
  /**
   * <pre>
   * Message Reply (Audio STREAM)
   * </pre>
   *
   * Protobuf type {@code asr_service.transcription_stream}
   */
  public  static final class transcription_stream extends
      com.google.protobuf.GeneratedMessageLite<
          transcription_stream, transcription_stream.Builder> implements
      // @@protoc_insertion_point(message_implements:asr_service.transcription_stream)
      transcription_streamOrBuilder {
    private transcription_stream() {
    }
    public static final int TEXT_FIELD_NUMBER = 1;
    private com.google.protobuf.StringValue text_;
    /**
     * <code>.google.protobuf.StringValue text = 1;</code>
     */
    @Override
    public boolean hasText() {
      return text_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue text = 1;</code>
     */
    @Override
    public com.google.protobuf.StringValue getText() {
      return text_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : text_;
    }
    /**
     * <code>.google.protobuf.StringValue text = 1;</code>
     */
    private void setText(com.google.protobuf.StringValue value) {
      value.getClass();
  text_ = value;
      
      }
    /**
     * <code>.google.protobuf.StringValue text = 1;</code>
     */
    @SuppressWarnings({"ReferenceEquality"})
    private void mergeText(com.google.protobuf.StringValue value) {
      value.getClass();
  if (text_ != null &&
          text_ != com.google.protobuf.StringValue.getDefaultInstance()) {
        text_ =
          com.google.protobuf.StringValue.newBuilder(text_).mergeFrom(value).buildPartial();
      } else {
        text_ = value;
      }
      
    }
    /**
     * <code>.google.protobuf.StringValue text = 1;</code>
     */
    private void clearText() {  text_ = null;
      
    }

    public static final int ID_FIELD_NUMBER = 2;
    private com.google.protobuf.StringValue id_;
    /**
     * <code>.google.protobuf.StringValue id = 2;</code>
     */
    @Override
    public boolean hasId() {
      return id_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue id = 2;</code>
     */
    @Override
    public com.google.protobuf.StringValue getId() {
      return id_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : id_;
    }
    /**
     * <code>.google.protobuf.StringValue id = 2;</code>
     */
    private void setId(com.google.protobuf.StringValue value) {
      value.getClass();
  id_ = value;
      
      }
    /**
     * <code>.google.protobuf.StringValue id = 2;</code>
     */
    @SuppressWarnings({"ReferenceEquality"})
    private void mergeId(com.google.protobuf.StringValue value) {
      value.getClass();
  if (id_ != null &&
          id_ != com.google.protobuf.StringValue.getDefaultInstance()) {
        id_ =
          com.google.protobuf.StringValue.newBuilder(id_).mergeFrom(value).buildPartial();
      } else {
        id_ = value;
      }
      
    }
    /**
     * <code>.google.protobuf.StringValue id = 2;</code>
     */
    private void clearId() {  id_ = null;
      
    }

    public static final int FINAL_FIELD_NUMBER = 3;
    private com.google.protobuf.BoolValue final_;
    /**
     * <code>.google.protobuf.BoolValue final = 3;</code>
     */
    @Override
    public boolean hasFinal() {
      return final_ != null;
    }
    /**
     * <code>.google.protobuf.BoolValue final = 3;</code>
     */
    @Override
    public com.google.protobuf.BoolValue getFinal() {
      return final_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : final_;
    }
    /**
     * <code>.google.protobuf.BoolValue final = 3;</code>
     */
    private void setFinal(com.google.protobuf.BoolValue value) {
      value.getClass();
  final_ = value;
      
      }
    /**
     * <code>.google.protobuf.BoolValue final = 3;</code>
     */
    @SuppressWarnings({"ReferenceEquality"})
    private void mergeFinal(com.google.protobuf.BoolValue value) {
      value.getClass();
  if (final_ != null &&
          final_ != com.google.protobuf.BoolValue.getDefaultInstance()) {
        final_ =
          com.google.protobuf.BoolValue.newBuilder(final_).mergeFrom(value).buildPartial();
      } else {
        final_ = value;
      }
      
    }
    /**
     * <code>.google.protobuf.BoolValue final = 3;</code>
     */
    private void clearFinal() {  final_ = null;
      
    }

    public static Asr.transcription_stream parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Asr.transcription_stream parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Asr.transcription_stream parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Asr.transcription_stream parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Asr.transcription_stream parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Asr.transcription_stream parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Asr.transcription_stream parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Asr.transcription_stream parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Asr.transcription_stream parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Asr.transcription_stream parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Asr.transcription_stream parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Asr.transcription_stream parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(Asr.transcription_stream prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Message Reply (Audio STREAM)
     * </pre>
     *
     * Protobuf type {@code asr_service.transcription_stream}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Asr.transcription_stream, Builder> implements
        // @@protoc_insertion_point(builder_implements:asr_service.transcription_stream)
        Asr.transcription_streamOrBuilder {
      // Construct using asr_service.Asr.transcription_stream.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.google.protobuf.StringValue text = 1;</code>
       */
      @Override
      public boolean hasText() {
        return instance.hasText();
      }
      /**
       * <code>.google.protobuf.StringValue text = 1;</code>
       */
      @Override
      public com.google.protobuf.StringValue getText() {
        return instance.getText();
      }
      /**
       * <code>.google.protobuf.StringValue text = 1;</code>
       */
      public Builder setText(com.google.protobuf.StringValue value) {
        copyOnWrite();
        instance.setText(value);
        return this;
        }
      /**
       * <code>.google.protobuf.StringValue text = 1;</code>
       */
      public Builder setText(
          com.google.protobuf.StringValue.Builder builderForValue) {
        copyOnWrite();
        instance.setText(builderForValue.build());
        return this;
      }
      /**
       * <code>.google.protobuf.StringValue text = 1;</code>
       */
      public Builder mergeText(com.google.protobuf.StringValue value) {
        copyOnWrite();
        instance.mergeText(value);
        return this;
      }
      /**
       * <code>.google.protobuf.StringValue text = 1;</code>
       */
      public Builder clearText() {  copyOnWrite();
        instance.clearText();
        return this;
      }

      /**
       * <code>.google.protobuf.StringValue id = 2;</code>
       */
      @Override
      public boolean hasId() {
        return instance.hasId();
      }
      /**
       * <code>.google.protobuf.StringValue id = 2;</code>
       */
      @Override
      public com.google.protobuf.StringValue getId() {
        return instance.getId();
      }
      /**
       * <code>.google.protobuf.StringValue id = 2;</code>
       */
      public Builder setId(com.google.protobuf.StringValue value) {
        copyOnWrite();
        instance.setId(value);
        return this;
        }
      /**
       * <code>.google.protobuf.StringValue id = 2;</code>
       */
      public Builder setId(
          com.google.protobuf.StringValue.Builder builderForValue) {
        copyOnWrite();
        instance.setId(builderForValue.build());
        return this;
      }
      /**
       * <code>.google.protobuf.StringValue id = 2;</code>
       */
      public Builder mergeId(com.google.protobuf.StringValue value) {
        copyOnWrite();
        instance.mergeId(value);
        return this;
      }
      /**
       * <code>.google.protobuf.StringValue id = 2;</code>
       */
      public Builder clearId() {  copyOnWrite();
        instance.clearId();
        return this;
      }

      /**
       * <code>.google.protobuf.BoolValue final = 3;</code>
       */
      @Override
      public boolean hasFinal() {
        return instance.hasFinal();
      }
      /**
       * <code>.google.protobuf.BoolValue final = 3;</code>
       */
      @Override
      public com.google.protobuf.BoolValue getFinal() {
        return instance.getFinal();
      }
      /**
       * <code>.google.protobuf.BoolValue final = 3;</code>
       */
      public Builder setFinal(com.google.protobuf.BoolValue value) {
        copyOnWrite();
        instance.setFinal(value);
        return this;
        }
      /**
       * <code>.google.protobuf.BoolValue final = 3;</code>
       */
      public Builder setFinal(
          com.google.protobuf.BoolValue.Builder builderForValue) {
        copyOnWrite();
        instance.setFinal(builderForValue.build());
        return this;
      }
      /**
       * <code>.google.protobuf.BoolValue final = 3;</code>
       */
      public Builder mergeFinal(com.google.protobuf.BoolValue value) {
        copyOnWrite();
        instance.mergeFinal(value);
        return this;
      }
      /**
       * <code>.google.protobuf.BoolValue final = 3;</code>
       */
      public Builder clearFinal() {  copyOnWrite();
        instance.clearFinal();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:asr_service.transcription_stream)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Asr.transcription_stream();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "text_",
              "id_",
              "final_",
            };
            String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\t\u0002\t\u0003" +
                "\t";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<Asr.transcription_stream> parser = PARSER;
          if (parser == null) {
            synchronized (Asr.transcription_stream.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<Asr.transcription_stream>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:asr_service.transcription_stream)
    private static final Asr.transcription_stream DEFAULT_INSTANCE;
    static {
      transcription_stream defaultInstance = new transcription_stream();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        transcription_stream.class, defaultInstance);
    }

    public static Asr.transcription_stream getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<transcription_stream> PARSER;

    public static com.google.protobuf.Parser<transcription_stream> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface transcription_blobOrBuilder extends
      // @@protoc_insertion_point(interface_extends:asr_service.transcription_blob)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.google.protobuf.StringValue transcription = 1;</code>
     * @return Whether the transcription field is set.
     */
    boolean hasTranscription();
    /**
     * <code>.google.protobuf.StringValue transcription = 1;</code>
     * @return The transcription.
     */
    com.google.protobuf.StringValue getTranscription();

    /**
     * <code>.google.protobuf.Int32Value sampleRate = 2;</code>
     * @return Whether the sampleRate field is set.
     */
    boolean hasSampleRate();
    /**
     * <code>.google.protobuf.Int32Value sampleRate = 2;</code>
     * @return The sampleRate.
     */
    com.google.protobuf.Int32Value getSampleRate();
  }
  /**
   * <pre>
   * Message Reply (Audio BLOB)
   * </pre>
   *
   * Protobuf type {@code asr_service.transcription_blob}
   */
  public  static final class transcription_blob extends
      com.google.protobuf.GeneratedMessageLite<
          transcription_blob, transcription_blob.Builder> implements
      // @@protoc_insertion_point(message_implements:asr_service.transcription_blob)
      transcription_blobOrBuilder {
    private transcription_blob() {
    }
    public static final int TRANSCRIPTION_FIELD_NUMBER = 1;
    private com.google.protobuf.StringValue transcription_;
    /**
     * <code>.google.protobuf.StringValue transcription = 1;</code>
     */
    @Override
    public boolean hasTranscription() {
      return transcription_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue transcription = 1;</code>
     */
    @Override
    public com.google.protobuf.StringValue getTranscription() {
      return transcription_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : transcription_;
    }
    /**
     * <code>.google.protobuf.StringValue transcription = 1;</code>
     */
    private void setTranscription(com.google.protobuf.StringValue value) {
      value.getClass();
  transcription_ = value;
      
      }
    /**
     * <code>.google.protobuf.StringValue transcription = 1;</code>
     */
    @SuppressWarnings({"ReferenceEquality"})
    private void mergeTranscription(com.google.protobuf.StringValue value) {
      value.getClass();
  if (transcription_ != null &&
          transcription_ != com.google.protobuf.StringValue.getDefaultInstance()) {
        transcription_ =
          com.google.protobuf.StringValue.newBuilder(transcription_).mergeFrom(value).buildPartial();
      } else {
        transcription_ = value;
      }
      
    }
    /**
     * <code>.google.protobuf.StringValue transcription = 1;</code>
     */
    private void clearTranscription() {  transcription_ = null;
      
    }

    public static final int SAMPLERATE_FIELD_NUMBER = 2;
    private com.google.protobuf.Int32Value sampleRate_;
    /**
     * <code>.google.protobuf.Int32Value sampleRate = 2;</code>
     */
    @Override
    public boolean hasSampleRate() {
      return sampleRate_ != null;
    }
    /**
     * <code>.google.protobuf.Int32Value sampleRate = 2;</code>
     */
    @Override
    public com.google.protobuf.Int32Value getSampleRate() {
      return sampleRate_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : sampleRate_;
    }
    /**
     * <code>.google.protobuf.Int32Value sampleRate = 2;</code>
     */
    private void setSampleRate(com.google.protobuf.Int32Value value) {
      value.getClass();
  sampleRate_ = value;
      
      }
    /**
     * <code>.google.protobuf.Int32Value sampleRate = 2;</code>
     */
    @SuppressWarnings({"ReferenceEquality"})
    private void mergeSampleRate(com.google.protobuf.Int32Value value) {
      value.getClass();
  if (sampleRate_ != null &&
          sampleRate_ != com.google.protobuf.Int32Value.getDefaultInstance()) {
        sampleRate_ =
          com.google.protobuf.Int32Value.newBuilder(sampleRate_).mergeFrom(value).buildPartial();
      } else {
        sampleRate_ = value;
      }
      
    }
    /**
     * <code>.google.protobuf.Int32Value sampleRate = 2;</code>
     */
    private void clearSampleRate() {  sampleRate_ = null;
      
    }

    public static Asr.transcription_blob parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Asr.transcription_blob parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Asr.transcription_blob parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Asr.transcription_blob parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Asr.transcription_blob parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Asr.transcription_blob parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Asr.transcription_blob parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Asr.transcription_blob parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Asr.transcription_blob parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Asr.transcription_blob parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Asr.transcription_blob parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Asr.transcription_blob parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(Asr.transcription_blob prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Message Reply (Audio BLOB)
     * </pre>
     *
     * Protobuf type {@code asr_service.transcription_blob}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Asr.transcription_blob, Builder> implements
        // @@protoc_insertion_point(builder_implements:asr_service.transcription_blob)
        Asr.transcription_blobOrBuilder {
      // Construct using asr_service.Asr.transcription_blob.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.google.protobuf.StringValue transcription = 1;</code>
       */
      @Override
      public boolean hasTranscription() {
        return instance.hasTranscription();
      }
      /**
       * <code>.google.protobuf.StringValue transcription = 1;</code>
       */
      @Override
      public com.google.protobuf.StringValue getTranscription() {
        return instance.getTranscription();
      }
      /**
       * <code>.google.protobuf.StringValue transcription = 1;</code>
       */
      public Builder setTranscription(com.google.protobuf.StringValue value) {
        copyOnWrite();
        instance.setTranscription(value);
        return this;
        }
      /**
       * <code>.google.protobuf.StringValue transcription = 1;</code>
       */
      public Builder setTranscription(
          com.google.protobuf.StringValue.Builder builderForValue) {
        copyOnWrite();
        instance.setTranscription(builderForValue.build());
        return this;
      }
      /**
       * <code>.google.protobuf.StringValue transcription = 1;</code>
       */
      public Builder mergeTranscription(com.google.protobuf.StringValue value) {
        copyOnWrite();
        instance.mergeTranscription(value);
        return this;
      }
      /**
       * <code>.google.protobuf.StringValue transcription = 1;</code>
       */
      public Builder clearTranscription() {  copyOnWrite();
        instance.clearTranscription();
        return this;
      }

      /**
       * <code>.google.protobuf.Int32Value sampleRate = 2;</code>
       */
      @Override
      public boolean hasSampleRate() {
        return instance.hasSampleRate();
      }
      /**
       * <code>.google.protobuf.Int32Value sampleRate = 2;</code>
       */
      @Override
      public com.google.protobuf.Int32Value getSampleRate() {
        return instance.getSampleRate();
      }
      /**
       * <code>.google.protobuf.Int32Value sampleRate = 2;</code>
       */
      public Builder setSampleRate(com.google.protobuf.Int32Value value) {
        copyOnWrite();
        instance.setSampleRate(value);
        return this;
        }
      /**
       * <code>.google.protobuf.Int32Value sampleRate = 2;</code>
       */
      public Builder setSampleRate(
          com.google.protobuf.Int32Value.Builder builderForValue) {
        copyOnWrite();
        instance.setSampleRate(builderForValue.build());
        return this;
      }
      /**
       * <code>.google.protobuf.Int32Value sampleRate = 2;</code>
       */
      public Builder mergeSampleRate(com.google.protobuf.Int32Value value) {
        copyOnWrite();
        instance.mergeSampleRate(value);
        return this;
      }
      /**
       * <code>.google.protobuf.Int32Value sampleRate = 2;</code>
       */
      public Builder clearSampleRate() {  copyOnWrite();
        instance.clearSampleRate();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:asr_service.transcription_blob)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Asr.transcription_blob();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "transcription_",
              "sampleRate_",
            };
            String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\t\u0002\t";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<Asr.transcription_blob> parser = PARSER;
          if (parser == null) {
            synchronized (Asr.transcription_blob.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<Asr.transcription_blob>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:asr_service.transcription_blob)
    private static final Asr.transcription_blob DEFAULT_INSTANCE;
    static {
      transcription_blob defaultInstance = new transcription_blob();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        transcription_blob.class, defaultInstance);
    }

    public static Asr.transcription_blob getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<transcription_blob> PARSER;

    public static com.google.protobuf.Parser<transcription_blob> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
